import type { LucideIcon } from "lucide-react";
import {
  Home, BarChart2, ReceiptText, CreditCard, Wallet, BookMarked,
  Users, FileText, Truck, Package, ListTodo, Calendar,
  CalendarRange, Timer, Sparkles, CheckSquare, ScanLine, Network,
  Search, Zap, Brain, Share2, Building2, Banknote, ThumbsUp,
  BookOpen, MessageSquare, Target, FolderOpen, Lock,
  StickyNote, CalendarPlus, ShoppingCart, Landmark, ScrollText,
  Store, Briefcase, Bot, TrendingUp, Contact2, PenLine, Globe,
  QrCode, ShoppingBag, Mail, Layout,
} from "lucide-react";

export type AppCategory =
  | "accueil"
  | "finance"
  | "commercial"
  | "operations"
  | "documents"
  | "intelligence"
  | "gestion";

export interface AppEntry {
  id: string;
  name: string;
  icon: LucideIcon;
  route: string;
  category: AppCategory;
  description: string;
  permission: "free" | "premium";
  keywords: string[];
}

export const CATEGORY_LABELS: Record<AppCategory, string> = {
  accueil:      "Accueil",
  finance:      "Finance",
  commercial:   "Commercial",
  operations:   "Opérations",
  documents:    "Documents",
  intelligence: "Intelligence",
  gestion:      "Gestion",
};

export const APP_REGISTRY: readonly AppEntry[] = [
  {
    id: "accueil",
    name: "Accueil",
    icon: Home,
    route: "/client",
    category: "accueil",
    description: "Tableau de bord principal",
    permission: "free",
    keywords: ["home", "accueil", "dashboard", "hub"],
  },
  {
    id: "dashboard",
    name: "Tableau de bord",
    icon: BarChart2,
    route: "/client/dashboard",
    category: "accueil",
    description: "Vue synthétique de l'activité",
    permission: "premium",
    keywords: ["stats", "kpi", "tableau", "bord", "analytique"],
  },
  {
    id: "factures",
    name: "Factures & Devis",
    icon: ReceiptText,
    route: "/client/factures",
    category: "finance",
    description: "Créer et gérer factures, devis, avoir",
    permission: "free",
    keywords: ["facture", "devis", "avoir", "invoice", "paiement"],
  },
  {
    id: "depenses",
    name: "Dépenses",
    icon: CreditCard,
    route: "/client/depenses",
    category: "finance",
    description: "Suivi des dépenses professionnelles",
    permission: "premium",
    keywords: ["dépense", "charge", "note de frais", "expense"],
  },
  {
    id: "tresorerie",
    name: "Trésorerie",
    icon: Wallet,
    route: "/client/tresorerie",
    category: "finance",
    description: "Flux de trésorerie et prévisions",
    permission: "premium",
    keywords: ["trésorerie", "cash", "flux", "solde", "banque"],
  },
  {
    id: "comptabilite",
    name: "Comptabilité",
    icon: BookMarked,
    route: "/client/comptabilite",
    category: "finance",
    description: "Journaux comptables et TVA",
    permission: "premium",
    keywords: ["comptabilité", "TVA", "journal", "bilan", "compte"],
  },
  {
    id: "crm",
    name: "CRM",
    icon: Users,
    route: "/client/crm",
    category: "commercial",
    description: "Gestion clients et prospects",
    permission: "premium",
    keywords: ["crm", "client", "prospect", "contact", "relation"],
  },
  {
    id: "contrats",
    name: "Contrats",
    icon: FileText,
    route: "/client/contrats",
    category: "commercial",
    description: "Rédaction et suivi des contrats",
    permission: "premium",
    keywords: ["contrat", "accord", "convention", "document juridique"],
  },
  {
    id: "fournisseurs",
    name: "Fournisseurs",
    icon: Truck,
    route: "/client/fournisseurs",
    category: "commercial",
    description: "Annuaire et évaluation des fournisseurs",
    permission: "premium",
    keywords: ["fournisseur", "prestataire", "achats", "supply"],
  },
  {
    id: "stocks",
    name: "Stocks",
    icon: Package,
    route: "/client/stocks",
    category: "commercial",
    description: "Gestion des stocks et inventaires",
    permission: "premium",
    keywords: ["stock", "inventaire", "produit", "entrepôt"],
  },
  {
    id: "productivite",
    name: "Tâches",
    icon: ListTodo,
    route: "/client/productivite",
    category: "operations",
    description: "Gestion des tâches et projets",
    permission: "premium",
    keywords: ["tâche", "todo", "kanban", "projet", "productivité"],
  },
  {
    id: "planning",
    name: "Planning",
    icon: Calendar,
    route: "/client/planning",
    category: "operations",
    description: "Agenda et planification",
    permission: "free",
    keywords: ["planning", "agenda", "calendrier", "rendez-vous", "événement"],
  },
  {
    id: "equipe",
    name: "Équipe",
    icon: CalendarRange,
    route: "/client/equipe",
    category: "operations",
    description: "Gestion de l'équipe et des congés",
    permission: "premium",
    keywords: ["équipe", "employé", "rh", "congé", "présence"],
  },
  {
    id: "espaces",
    name: "Espaces Privés",
    icon: Lock,
    route: "/client/espaces",
    category: "operations",
    description: "Espaces collaboratifs sécurisés",
    permission: "premium",
    keywords: ["espace", "privé", "collaboration", "sécurisé"],
  },
  {
    id: "chrono",
    name: "Chronomètre",
    icon: Timer,
    route: "/client/chrono",
    category: "operations",
    description: "Suivi du temps de travail",
    permission: "premium",
    keywords: ["chrono", "temps", "minuteur", "pomodoro", "time tracking"],
  },
  {
    id: "ai-docs",
    name: "DOC IA",
    icon: Sparkles,
    route: "/client/ai-docs",
    category: "documents",
    description: "Génération de documents par IA",
    permission: "free",
    keywords: ["doc", "document", "IA", "génération", "contenu", "rédaction"],
  },
  {
    id: "checklists",
    name: "Checklists",
    icon: CheckSquare,
    route: "/client/checklists",
    category: "documents",
    description: "Checklists et procédures",
    permission: "premium",
    keywords: ["checklist", "liste", "procédure", "vérification"],
  },
  {
    id: "scanner",
    name: "Scanner",
    icon: ScanLine,
    route: "/client/scanner",
    category: "documents",
    description: "Numérisation et analyse de documents",
    permission: "premium",
    keywords: ["scanner", "scan", "ocr", "numériser", "photo"],
  },
  {
    id: "mindmap",
    name: "Mind Map",
    icon: Network,
    route: "/client/mindmap",
    category: "documents",
    description: "Cartes mentales et brainstorming",
    permission: "premium",
    keywords: ["mindmap", "carte mentale", "brainstorming", "idée"],
  },
  {
    id: "sourcing",
    name: "Sourcing IA",
    icon: Search,
    route: "/client/sourcing",
    category: "intelligence",
    description: "Sourcing fournisseurs et appels d'offres",
    permission: "premium",
    keywords: ["sourcing", "appel offre", "fournisseur", "import", "achat"],
  },
  {
    id: "assistant",
    name: "Assistant IA",
    icon: Zap,
    route: "/client/assistant",
    category: "intelligence",
    description: "Assistant intelligent pour votre business",
    permission: "premium",
    keywords: ["assistant", "IA", "chat", "aide", "bot"],
  },
  {
    id: "projets",
    name: "Projets",
    icon: FolderOpen,
    route: "/client/projets",
    category: "intelligence",
    description: "Gestion de projets avancée",
    permission: "premium",
    keywords: ["projet", "gestion", "jalons", "sprint", "livrable"],
  },
  {
    id: "reseaux-sociaux",
    name: "Réseaux Sociaux",
    icon: Share2,
    route: "/client/reseaux-sociaux",
    category: "intelligence",
    description: "Gestion des réseaux sociaux",
    permission: "premium",
    keywords: ["réseaux", "sociaux", "instagram", "linkedin", "post"],
  },
  {
    id: "coaching-ia",
    name: "Coaching IA",
    icon: Brain,
    route: "/coaching-ia/espace",
    category: "intelligence",
    description: "Formation et coaching personnalisé par IA",
    permission: "premium",
    keywords: ["coaching", "formation", "apprentissage", "cours", "compétence"],
  },
  {
    id: "portail",
    name: "Portail Client",
    icon: Building2,
    route: "/client/portail",
    category: "gestion",
    description: "Espace client en marque blanche",
    permission: "premium",
    keywords: ["portail", "client", "espace", "marque blanche"],
  },
  {
    id: "paie",
    name: "Paie & RH",
    icon: Banknote,
    route: "/client/paie",
    category: "gestion",
    description: "Bulletins de paie et gestion RH",
    permission: "premium",
    keywords: ["paie", "salaire", "rh", "bulletin", "cotisation"],
  },
  {
    id: "reputation",
    name: "Réputation",
    icon: ThumbsUp,
    route: "/client/reputation",
    category: "gestion",
    description: "Gestion de l'e-réputation",
    permission: "premium",
    keywords: ["réputation", "avis", "google", "note", "feedback"],
  },
  {
    id: "blog",
    name: "Blog",
    icon: BookOpen,
    route: "/client/blog",
    category: "gestion",
    description: "Création de contenu blog",
    permission: "premium",
    keywords: ["blog", "article", "contenu", "seo", "rédaction"],
  },
  {
    id: "temoignages",
    name: "Témoignages",
    icon: MessageSquare,
    route: "/client/temoignages",
    category: "gestion",
    description: "Collecte de témoignages clients",
    permission: "premium",
    keywords: ["témoignage", "avis", "client", "review"],
  },
  {
    id: "planification",
    name: "Planification",
    icon: Target,
    route: "/client/planification",
    category: "gestion",
    description: "Planification stratégique et objectifs",
    permission: "premium",
    keywords: ["planification", "objectif", "stratégie", "okr", "plan"],
  },

  /* ── Pages existantes manquantes ── */
  {
    id: "bloc-notes",
    name: "Bloc-notes",
    icon: StickyNote,
    route: "/client/bloc-notes",
    category: "documents",
    description: "Notes, cahiers et prise de notes rapide",
    permission: "free",
    keywords: ["note", "bloc", "cahier", "écrire", "mémo"],
  },
  {
    id: "rendez-vous",
    name: "Rendez-vous",
    icon: CalendarPlus,
    route: "/client/rendez-vous",
    category: "operations",
    description: "Prise de rendez-vous et agenda client",
    permission: "premium",
    keywords: ["rdv", "rendez-vous", "réservation", "créneau", "agenda"],
  },
  {
    id: "caisse",
    name: "Caisse",
    icon: ShoppingCart,
    route: "/client/caisse",
    category: "finance",
    description: "Caisse enregistreuse et point de vente",
    permission: "premium",
    keywords: ["caisse", "pos", "vente", "encaissement", "ticket"],
  },
  {
    id: "banque",
    name: "Banque",
    icon: Landmark,
    route: "/client/banque",
    category: "finance",
    description: "Compte bancaire et suivi des transactions",
    permission: "premium",
    keywords: ["banque", "compte", "virement", "transaction", "relevé"],
  },
  {
    id: "declarations",
    name: "Déclarations",
    icon: ScrollText,
    route: "/client/declarations",
    category: "finance",
    description: "Déclarations fiscales et TVA",
    permission: "premium",
    keywords: ["déclaration", "tva", "impôt", "fiscal", "cfe", "urssaf"],
  },
  {
    id: "paiements",
    name: "Liens de Paiement",
    icon: QrCode,
    route: "/client/paiements",
    category: "finance",
    description: "Liens de paiement et QR codes",
    permission: "premium",
    keywords: ["paiement", "lien", "qr", "stripe", "checkout"],
  },
  {
    id: "marketplace",
    name: "Marketplace",
    icon: Store,
    route: "/client/marketplace",
    category: "commercial",
    description: "Place de marché de services professionnels",
    permission: "premium",
    keywords: ["marketplace", "marché", "service", "prestataire", "freelance"],
  },
  {
    id: "boutique",
    name: "Boutique",
    icon: ShoppingBag,
    route: "/client/boutique",
    category: "commercial",
    description: "Boutique en ligne et catalogue produits",
    permission: "premium",
    keywords: ["boutique", "shop", "produit", "vente", "catalogue"],
  },
  {
    id: "email-marketing",
    name: "Email Marketing",
    icon: Mail,
    route: "/client/email-marketing",
    category: "commercial",
    description: "Campagnes d'emailing et newsletters",
    permission: "premium",
    keywords: ["email", "campagne", "newsletter", "mailing", "emailing"],
  },
  {
    id: "agences",
    name: "Agences",
    icon: Briefcase,
    route: "/client/agences",
    category: "commercial",
    description: "Annuaire des agences et partenaires",
    permission: "premium",
    keywords: ["agence", "partenaire", "prestataire", "réseau"],
  },
  {
    id: "chatbot",
    name: "Chatbot IA",
    icon: Bot,
    route: "/client/chatbot",
    category: "intelligence",
    description: "Création de chatbots IA personnalisés",
    permission: "premium",
    keywords: ["chatbot", "bot", "ia", "agent", "conversation"],
  },
  {
    id: "analytics",
    name: "Analytics",
    icon: TrendingUp,
    route: "/client/analytics",
    category: "intelligence",
    description: "Statistiques et analytique web",
    permission: "premium",
    keywords: ["analytics", "stats", "trafic", "audience", "conversion"],
  },
  {
    id: "signature",
    name: "Signature",
    icon: PenLine,
    route: "/client/signature",
    category: "documents",
    description: "Signature électronique de documents",
    permission: "premium",
    keywords: ["signature", "signer", "électronique", "document", "contrat"],
  },
  {
    id: "carte-visite",
    name: "Carte de Visite",
    icon: Contact2,
    route: "/client/carte-visite",
    category: "gestion",
    description: "Création de cartes de visite numériques",
    permission: "premium",
    keywords: ["carte", "visite", "contact", "qr", "profil"],
  },
  {
    id: "site-web",
    name: "Site Web",
    icon: Globe,
    route: "/client/site-web",
    category: "gestion",
    description: "Constructeur de site web",
    permission: "premium",
    keywords: ["site", "web", "vitrine", "landing", "page"],
  },
  {
    id: "mes-sites",
    name: "Mes Sites",
    icon: Layout,
    route: "/client/mes-sites",
    category: "gestion",
    description: "Gestion de vos sites et pages web",
    permission: "premium",
    keywords: ["site", "page", "web", "déploiement", "domaine"],
  },
] as const;

export function getAppById(id: string): AppEntry | undefined {
  return APP_REGISTRY.find(a => a.id === id);
}

export function getAppsByCategory(cat: AppCategory): AppEntry[] {
  return APP_REGISTRY.filter(a => a.category === cat) as AppEntry[];
}

export const FREE_NAV_IDS = ["accueil", "factures", "planning", "ai-docs"] as const;
