export interface Industry {
  slug: string;
  label: string;
  category: string;
  color: string;
  tagline: string;
  description: string;
  apps: string[]; // slugs d'apps DJAMA recommandées
}

export const INDUSTRIES_DATA: Industry[] = [
  // COMMERCE DE DÉTAIL
  {
    slug: "boutique-pret-a-porter",
    label: "Boutique & Prêt-à-porter",
    category: "Commerce de détail",
    color: "#3b82f6",
    tagline: "Gérez vos stocks, ventes et clients en un seul endroit.",
    description: "De la réception des marchandises à l'encaissement, DJAMA simplifie la gestion quotidienne de votre boutique de vêtements.",
    apps: ["factures", "crm", "stocks", "paie"],
  },
  {
    slug: "epicerie-supermarche",
    label: "Épicerie & Supermarché",
    category: "Commerce de détail",
    color: "#3b82f6",
    tagline: "Stocks en temps réel, caisse rapide, fournisseurs maîtrisés.",
    description: "Suivez vos stocks à la référence près, gérez vos commandes fournisseurs et gardez une trésorerie saine.",
    apps: ["stocks", "factures", "fournisseurs", "tresorerie"],
  },
  {
    slug: "quincaillerie-bricolage",
    label: "Quincaillerie & Bricolage",
    category: "Commerce de détail",
    color: "#3b82f6",
    tagline: "Des milliers de références, zéro rupture de stock.",
    description: "Gérez un catalogue étendu, anticipez les réapprovisionnements et suivez vos marges article par article.",
    apps: ["stocks", "factures", "fournisseurs", "comptabilite"],
  },
  {
    slug: "librairie-papeterie",
    label: "Librairie & Papeterie",
    category: "Commerce de détail",
    color: "#3b82f6",
    tagline: "Référencez, vendez et fidélisez vos clients lecteurs.",
    description: "Cataloguez des milliers de titres, gérez vos commandes éditeurs et proposez des devis scolaires groupés.",
    apps: ["stocks", "factures", "crm", "fournisseurs"],
  },
  {
    slug: "electronique-telephonie",
    label: "Électronique & Téléphonie",
    category: "Commerce de détail",
    color: "#3b82f6",
    tagline: "SAV, garanties et stocks sous contrôle.",
    description: "Suivez les numéros de série, gérez le SAV et les garanties, et pilotez votre rentabilité par produit.",
    apps: ["stocks", "factures", "crm", "comptabilite"],
  },
  {
    slug: "bijouterie-cadeaux",
    label: "Bijouterie & Cadeaux",
    category: "Commerce de détail",
    color: "#3b82f6",
    tagline: "Valorisez chaque article et chouchoutez vos clients.",
    description: "Gérez un inventaire de valeur, proposez des devis personnalisés et construisez une relation client durable.",
    apps: ["crm", "factures", "stocks", "chatbot"],
  },

  // RESTAURATION & HÔTELLERIE
  {
    slug: "restaurant",
    label: "Restaurant",
    category: "Restauration & Hôtellerie",
    color: "#0d9488",
    tagline: "De la commande à la caisse, fluidifiez votre service.",
    description: "Gérez les réservations, les commandes en salle, les achats fournisseurs et la paie de votre équipe depuis DJAMA.",
    apps: ["factures", "planning", "paie", "fournisseurs"],
  },
  {
    slug: "fast-food-snack",
    label: "Fast-food & Snack",
    category: "Restauration & Hôtellerie",
    color: "#0d9488",
    tagline: "Rapidité en salle, rigueur en cuisine.",
    description: "Encaissements rapides, gestion des stocks alimentaires et planification des équipes pour un service fluide.",
    apps: ["factures", "stocks", "planning", "paie"],
  },
  {
    slug: "bar-cafe",
    label: "Bar & Café",
    category: "Restauration & Hôtellerie",
    color: "#0d9488",
    tagline: "Fidélisez vos habitués, maîtrisez vos achats.",
    description: "Suivez votre chiffre d'affaires en temps réel, gérez vos approvisionnements et fidélisez votre clientèle.",
    apps: ["factures", "crm", "stocks", "tresorerie"],
  },
  {
    slug: "boulangerie-patisserie",
    label: "Boulangerie & Pâtisserie",
    category: "Restauration & Hôtellerie",
    color: "#0d9488",
    tagline: "Gérez votre production, vos ventes et vos équipes.",
    description: "Planifiez votre production, suivez vos matières premières et gérez la paie de vos employés en quelques clics.",
    apps: ["stocks", "planning", "paie", "factures"],
  },
  {
    slug: "service-traiteur",
    label: "Service Traiteur",
    category: "Restauration & Hôtellerie",
    color: "#0d9488",
    tagline: "Devis, événements et logistique maîtrisés.",
    description: "Établissez des devis d'événements, gérez les commandes fournisseurs et coordonnez vos équipes sur le terrain.",
    apps: ["factures", "projets", "planning", "fournisseurs"],
  },
  {
    slug: "hotel-pension",
    label: "Hôtel & Pension",
    category: "Restauration & Hôtellerie",
    color: "#0d9488",
    tagline: "Reservations, facturation et équipes en un clic.",
    description: "Gérez vos réservations, établissez des factures clients, suivez la trésorerie et planifiez vos équipes d'entretien.",
    apps: ["factures", "crm", "planning", "tresorerie"],
  },

  // IMMOBILIER & BTP
  {
    slug: "agence-immobiliere",
    label: "Agence immobilière",
    category: "Immobilier & BTP",
    color: "#ef4444",
    tagline: "Portefeuille de biens, mandats et clients centralisés.",
    description: "Suivez vos mandats, gérez vos contacts acheteurs/vendeurs et automatisez vos relances commerciales.",
    apps: ["crm", "factures", "chatbot", "email-marketing"],
  },
  {
    slug: "construction-gros-oeuvre",
    label: "Construction & Gros œuvre",
    category: "Immobilier & BTP",
    color: "#ef4444",
    tagline: "Chantiers, devis et sous-traitants sous contrôle.",
    description: "Pilotez vos chantiers, gérez vos devis et factures d'avancement, et suivez vos sous-traitants.",
    apps: ["projets", "factures", "fournisseurs", "planning"],
  },
  {
    slug: "architecture-ingenierie",
    label: "Architecture & Ingénierie",
    category: "Immobilier & BTP",
    color: "#ef4444",
    tagline: "Projets, honoraires et collaborateurs bien gérés.",
    description: "Suivez l'avancement de vos projets, facturez vos honoraires à l'étape et gérez votre cabinet efficacement.",
    apps: ["projets", "factures", "planning", "comptabilite"],
  },
  {
    slug: "renovation-decoration",
    label: "Rénovation & Décoration",
    category: "Immobilier & BTP",
    color: "#ef4444",
    tagline: "Devis rapides, chantiers organisés, clients satisfaits.",
    description: "Établissez des devis détaillés, suivez l'avancement des travaux et gérez vos achats matériaux.",
    apps: ["factures", "projets", "fournisseurs", "crm"],
  },
  {
    slug: "plomberie-electricite",
    label: "Plomberie & Électricité",
    category: "Immobilier & BTP",
    color: "#ef4444",
    tagline: "Interventions planifiées, factures émises sur le terrain.",
    description: "Planifiez vos interventions, émettez des factures depuis votre téléphone et suivez vos encaissements.",
    apps: ["planning", "factures", "crm", "tresorerie"],
  },
  {
    slug: "promotion-immobiliere",
    label: "Promotion immobilière",
    category: "Immobilier & BTP",
    color: "#ef4444",
    tagline: "Programmes, réservations et comptabilité intégrés.",
    description: "Gérez vos programmes de vente, suivez les réservations et la comptabilité de vos opérations.",
    apps: ["crm", "factures", "comptabilite", "projets"],
  },

  // SERVICES PROFESSIONNELS
  {
    slug: "cabinet-comptable",
    label: "Cabinet comptable",
    category: "Services professionnels",
    color: "#6b7280",
    tagline: "Gérez vos dossiers clients et votre cabinet avec rigueur.",
    description: "Suivez vos dossiers clients, gérez votre facturation d'honoraires et pilotez la rentabilité de votre cabinet.",
    apps: ["comptabilite", "factures", "crm", "planning"],
  },
  {
    slug: "cabinet-juridique",
    label: "Cabinet juridique",
    category: "Services professionnels",
    color: "#6b7280",
    tagline: "Dossiers, temps passé et honoraires maîtrisés.",
    description: "Suivez vos dossiers, facturez au temps passé, gérez vos relances et gardez une vision claire de votre activité.",
    apps: ["factures", "projets", "crm", "comptabilite"],
  },
  {
    slug: "agence-communication",
    label: "Agence de communication",
    category: "Services professionnels",
    color: "#6b7280",
    tagline: "Projets créatifs, clients et finances en ordre.",
    description: "Gérez vos briefs, suivez l'avancement des projets, facturez à l'étape et fidélisez vos clients.",
    apps: ["projets", "factures", "crm", "email-marketing"],
  },
  {
    slug: "conseil-formation",
    label: "Conseil & Formation",
    category: "Services professionnels",
    color: "#6b7280",
    tagline: "Missions, sessions et revenus bien pilotés.",
    description: "Planifiez vos missions et sessions de formation, établissez vos conventions et suivez vos encaissements.",
    apps: ["planning", "factures", "crm", "comptabilite"],
  },
  {
    slug: "recrutement-rh",
    label: "Recrutement & RH",
    category: "Services professionnels",
    color: "#6b7280",
    tagline: "Candidats, clients et placements centralisés.",
    description: "Gérez votre vivier de candidats, suivez vos mandats clients et facturez vos commissions de placement.",
    apps: ["crm", "factures", "planning", "chatbot"],
  },
  {
    slug: "audit-certification",
    label: "Audit & Certification",
    category: "Services professionnels",
    color: "#6b7280",
    tagline: "Missions structurées, rapports professionnels.",
    description: "Planifiez vos missions, gérez votre équipe d'auditeurs et produisez des rapports professionnels.",
    apps: ["projets", "factures", "planning", "comptabilite"],
  },

  // SANTÉ & BIEN-ÊTRE
  {
    slug: "clinique-medicale",
    label: "Clinique médicale",
    category: "Santé & Bien-être",
    color: "#ec4899",
    tagline: "Patients, rendez-vous et facturation sécurisés.",
    description: "Gérez vos agendas médicaux, la facturation patients et la paie de votre personnel soignant.",
    apps: ["planning", "factures", "paie", "crm"],
  },
  {
    slug: "cabinet-dentaire",
    label: "Cabinet dentaire",
    category: "Santé & Bien-être",
    color: "#ec4899",
    tagline: "Agenda rempli, caisse équilibrée.",
    description: "Organisez vos rendez-vous, facturez vos actes et gérez vos approvisionnements en matériel dentaire.",
    apps: ["planning", "factures", "stocks", "tresorerie"],
  },
  {
    slug: "pharmacie",
    label: "Pharmacie",
    category: "Santé & Bien-être",
    color: "#ec4899",
    tagline: "Stocks médicaments, ventes et fournisseurs intégrés.",
    description: "Gérez votre stock de médicaments, vos commandes grossistes et votre comptabilité en conformité.",
    apps: ["stocks", "factures", "fournisseurs", "comptabilite"],
  },
  {
    slug: "salle-sport-fitness",
    label: "Salle de sport & Fitness",
    category: "Santé & Bien-être",
    color: "#ec4899",
    tagline: "Abonnements, coachs et planning coordonnés.",
    description: "Gérez vos abonnements membres, planifiez vos cours collectifs et suivez la paie de vos coachs.",
    apps: ["factures", "planning", "paie", "crm"],
  },
  {
    slug: "salon-beaute-coiffure",
    label: "Salon de beauté & Coiffure",
    category: "Santé & Bien-être",
    color: "#ec4899",
    tagline: "Réservations en ligne, fidélité et caisse simplifiée.",
    description: "Prenez des rendez-vous, fidélisez votre clientèle et gérez vos produits cosmétiques en stock.",
    apps: ["planning", "crm", "stocks", "factures"],
  },
  {
    slug: "bien-etre-spa",
    label: "Bien-être & Spa",
    category: "Santé & Bien-être",
    color: "#ec4899",
    tagline: "Expérience premium, gestion sans stress.",
    description: "Offrez une expérience client irréprochable avec une gestion fluide des réservations, paiements et équipes.",
    apps: ["planning", "crm", "factures", "paie"],
  },

  // TRANSPORT & LOGISTIQUE
  {
    slug: "transport-marchandises",
    label: "Transport de marchandises",
    category: "Transport & Logistique",
    color: "#f59e0b",
    tagline: "Tournées, bons de livraison et facturation optimisés.",
    description: "Planifiez vos tournées, émettez vos bons de livraison et facturez vos clients transporteurs.",
    apps: ["factures", "planning", "crm", "tresorerie"],
  },
  {
    slug: "demenagement",
    label: "Déménagement",
    category: "Transport & Logistique",
    color: "#f59e0b",
    tagline: "Devis rapides, équipes coordonnées, clients satisfaits.",
    description: "Établissez des devis en quelques minutes, planifiez vos équipes et suivez vos encaissements.",
    apps: ["factures", "planning", "crm", "paie"],
  },
  {
    slug: "location-vehicules",
    label: "Location de véhicules",
    category: "Transport & Logistique",
    color: "#f59e0b",
    tagline: "Flotte, réservations et contrats sous contrôle.",
    description: "Gérez votre flotte de véhicules, les réservations clients et la facturation des locations.",
    apps: ["factures", "crm", "planning", "comptabilite"],
  },
  {
    slug: "coursier-livraison",
    label: "Coursier & Livraison",
    category: "Transport & Logistique",
    color: "#f59e0b",
    tagline: "Commandes, livreurs et paiements fluides.",
    description: "Coordinateur vos livreurs, suivez les commandes en temps réel et facturez vos clients e-commerce.",
    apps: ["planning", "factures", "crm", "tresorerie"],
  },
  {
    slug: "import-export",
    label: "Import-Export",
    category: "Transport & Logistique",
    color: "#f59e0b",
    tagline: "Achats internationaux, ventes locales, comptabilité nette.",
    description: "Gérez vos commandes internationales, suivez vos coûts d'importation et pilotez votre rentabilité.",
    apps: ["fournisseurs", "factures", "comptabilite", "tresorerie"],
  },
  {
    slug: "transit-douane",
    label: "Transit & Douane",
    category: "Transport & Logistique",
    color: "#f59e0b",
    tagline: "Dossiers douaniers, clients et honoraires suivis.",
    description: "Gérez vos dossiers de transit, facturez vos prestations et suivez vos encaissements clients.",
    apps: ["factures", "projets", "crm", "comptabilite"],
  },

  // DIGITAL & TECH
  {
    slug: "developpement-web-mobile",
    label: "Développement web & Mobile",
    category: "Digital & Tech",
    color: "#8b5cf6",
    tagline: "Projets tech, clients et revenus bien gérés.",
    description: "Suivez vos projets de développement, facturez à l'étape et gérez vos contrats de maintenance.",
    apps: ["projets", "factures", "crm", "planning"],
  },
  {
    slug: "marketing-digital",
    label: "Marketing digital",
    category: "Digital & Tech",
    color: "#8b5cf6",
    tagline: "Campagnes, clients et ROI centralisés.",
    description: "Gérez vos clients, suivez vos campagnes, facturez vos prestations et pilotez votre agence.",
    apps: ["crm", "email-marketing", "factures", "projets"],
  },
  {
    slug: "ecommerce-marketplace",
    label: "E-commerce & Marketplace",
    category: "Digital & Tech",
    color: "#8b5cf6",
    tagline: "Commandes, stocks et expéditions synchronisés.",
    description: "Centralisez vos ventes multi-canaux, gérez vos stocks et automatisez votre facturation e-commerce.",
    apps: ["stocks", "factures", "crm", "email-marketing"],
  },
  {
    slug: "formation-informatique",
    label: "Formation informatique",
    category: "Digital & Tech",
    color: "#8b5cf6",
    tagline: "Sessions, apprenants et certifications gérés.",
    description: "Planifiez vos sessions de formation, gérez vos apprenants et facturez vos conventions.",
    apps: ["planning", "factures", "crm", "chatbot"],
  },
  {
    slug: "cybersecurite",
    label: "Cybersécurité",
    category: "Digital & Tech",
    color: "#8b5cf6",
    tagline: "Missions, audits et contrats bien structurés.",
    description: "Gérez vos missions d'audit, vos contrats de maintenance et la facturation de vos prestations.",
    apps: ["projets", "factures", "crm", "comptabilite"],
  },
  {
    slug: "production-audiovisuelle",
    label: "Production audiovisuelle",
    category: "Digital & Tech",
    color: "#8b5cf6",
    tagline: "Tournages, post-production et clients coordonnés.",
    description: "Gérez vos projets audiovisuels, planifiez vos équipes et facturez vos clients productions.",
    apps: ["projets", "planning", "factures", "crm"],
  },

  // AGRICULTURE & INDUSTRIE
  {
    slug: "agriculture-maraichage",
    label: "Agriculture & Maraîchage",
    category: "Agriculture & Industrie",
    color: "#10b981",
    tagline: "Récoltes, ventes et comptabilité agricole simplifiées.",
    description: "Suivez vos cultures, gérez vos ventes aux marchés et aux grossistes, et pilotez votre trésorerie agricole.",
    apps: ["factures", "stocks", "tresorerie", "comptabilite"],
  },
  {
    slug: "peche-aquaculture",
    label: "Pêche & Aquaculture",
    category: "Agriculture & Industrie",
    color: "#10b981",
    tagline: "Production, vente et traçabilité maîtrisées.",
    description: "Gérez votre production, vos ventes aux acheteurs locaux et exportateurs, et suivez votre rentabilité.",
    apps: ["factures", "stocks", "crm", "tresorerie"],
  },
  {
    slug: "agroalimentaire",
    label: "Agroalimentaire",
    category: "Agriculture & Industrie",
    color: "#10b981",
    tagline: "Production, stocks et distribution intégrés.",
    description: "Planifiez votre production, gérez vos stocks de matières premières et pilotez votre réseau de distribution.",
    apps: ["stocks", "factures", "fournisseurs", "planning"],
  },
  {
    slug: "textile-confection",
    label: "Textile & Confection",
    category: "Agriculture & Industrie",
    color: "#10b981",
    tagline: "Commandes, production et livraisons coordonnées.",
    description: "Gérez vos commandes clients, suivez votre production et pilotez votre réseau de sous-traitants.",
    apps: ["projets", "stocks", "factures", "fournisseurs"],
  },
  {
    slug: "artisanat-creation",
    label: "Artisanat & Création",
    category: "Agriculture & Industrie",
    color: "#10b981",
    tagline: "Créez, vendez et développez votre clientèle.",
    description: "Gérez vos commandes sur mesure, vos stocks de matériaux et développez votre clientèle locale et export.",
    apps: ["factures", "crm", "stocks", "email-marketing"],
  },
  {
    slug: "energie-renouvelable",
    label: "Énergie renouvelable",
    category: "Agriculture & Industrie",
    color: "#10b981",
    tagline: "Installations, contrats et maintenance pilotés.",
    description: "Gérez vos projets d'installation solaire, vos contrats de maintenance et votre facturation clients.",
    apps: ["projets", "factures", "crm", "planning"],
  },
];

export function getIndustryBySlug(slug: string): Industry | undefined {
  return INDUSTRIES_DATA.find((i) => i.slug === slug);
}

export const INDUSTRIES_BY_CATEGORY = (() => {
  const map = new Map<string, { color: string; items: Industry[] }>();
  for (const ind of INDUSTRIES_DATA) {
    if (!map.has(ind.category)) map.set(ind.category, { color: ind.color, items: [] });
    map.get(ind.category)!.items.push(ind);
  }
  return Array.from(map.entries()).map(([cat, { color, items }]) => ({ cat, color, items }));
})();
