import {
  Code2,
  ShoppingCart,
  Smartphone,
  LayoutDashboard,
  Video,
  Image as ImageIcon,
  Megaphone,
  FileText,
  ClipboardList,
  NotebookPen,
  Briefcase,
  BadgeCheck,
  Brain,
  GraduationCap,
  Building2,
  Globe,
  Landmark,
} from "lucide-react";

export type Service = {
  slug: string;
  title: string;
  excerpt: string;
  category:
    | "Digital"
    | "Création de contenu"
    | "Documents & Outils"
    | "Accompagnement"
    | "Coaching";
  /** "outil" = inclus dans l'abonnement → CTA vers /abonnement
   *  "prestation" = sur devis / contact → CTA vers /contact */
  serviceType: "outil" | "prestation";
  icon: React.ElementType;
  highlights: string[];
  titleEn?: string;
  excerptEn?: string;
  highlightsEn?: string[];
  ctaLabel?: string;
  ctaLabelEn?: string;
  ctaHref?: string;
};

export const services: Service[] = [
  // ── DIGITAL (prestations sur devis) ──────────────────────
  {
    slug: "site-vitrine",
    title: "Site vitrine / portfolio",
    excerpt: "Design premium, rapide, pensé conversion (pro & clean).",
    titleEn: "Showcase website / portfolio",
    excerptEn: "Premium design, fast, built for conversion — professional and clean.",
    category: "Digital",
    serviceType: "prestation",
    icon: Code2,
    highlights: ["UX premium", "Responsive", "SEO de base", "Sections sur mesure"],
    highlightsEn: ["Premium UX", "Responsive", "Basic SEO", "Custom sections"],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },
  {
    slug: "site-ecommerce",
    title: "Site e-commerce",
    excerpt: "Boutique moderne + pages produit + parcours simple.",
    titleEn: "E-commerce website",
    excerptEn: "Modern shop + product pages + seamless checkout journey.",
    category: "Digital",
    serviceType: "prestation",
    icon: ShoppingCart,
    highlights: ["Pages produit", "Panier", "Paiements PayPal/virement", "Optimisation confiance"],
    highlightsEn: ["Product pages", "Cart", "PayPal/bank transfer payments", "Trust optimisation"],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },
  {
    slug: "application-mobile",
    title: "Application mobile",
    excerpt: "Application propre & évolutive (UX, performance).",
    titleEn: "Mobile application",
    excerptEn: "Clean & scalable application — great UX, solid performance.",
    category: "Digital",
    serviceType: "prestation",
    icon: Smartphone,
    highlights: ["UX moderne", "Fonctionnalités utiles", "Évolutif", "Accompagnement"],
    highlightsEn: ["Modern UX", "Useful features", "Scalable", "Expert guidance"],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },
  {
    slug: "plateforme-web",
    title: "Plateforme / outil web sur mesure",
    excerpt: "Dashboard, comptes, outils internes — comme un mini-SaaS.",
    titleEn: "Custom web platform / tool",
    excerptEn: "Dashboard, accounts, internal tools — like a mini-SaaS.",
    category: "Digital",
    serviceType: "prestation",
    icon: LayoutDashboard,
    highlights: ["Espace client", "Gestion simple", "Branding", "Scalable"],
    highlightsEn: ["Client area", "Simple management", "Branding", "Scalable"],
    ctaLabel: "Démarrer un projet",
    ctaLabelEn: "Start a project",
    ctaHref: "/contact",
  },

  // ── CRÉATION DE CONTENU (prestations sur devis) ──────────
  {
    slug: "montage-video",
    title: "Montage vidéo pro",
    excerpt: "Reels, pubs, formats Instagram — style propre & premium.",
    titleEn: "Professional video editing",
    excerptEn: "Reels, ads, Instagram formats — clean and premium style.",
    category: "Création de contenu",
    serviceType: "prestation",
    icon: Video,
    highlights: ["Sous-titres", "Rythme pro", "Branding", "Formats réseaux sociaux"],
    highlightsEn: ["Subtitles", "Professional pacing", "Branding", "Social media formats"],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },
  {
    slug: "retouche-photo",
    title: "Retouche / montage photo",
    excerpt: "Visuels clean, retouche pro, cohérence de marque.",
    titleEn: "Photo retouching / editing",
    excerptEn: "Clean visuals, professional retouching, brand consistency.",
    category: "Création de contenu",
    serviceType: "prestation",
    icon: ImageIcon,
    highlights: ["Qualité pro", "Branding", "Posts", "Bannières"],
    highlightsEn: ["Professional quality", "Branding", "Posts", "Banners"],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },
  {
    slug: "visuels-publicitaires",
    title: "Visuels publicitaires",
    excerpt: "Posts & ads : design pro, impact et cohérence.",
    titleEn: "Advertising visuals",
    excerptEn: "Posts & ads: professional design, impact and brand consistency.",
    category: "Création de contenu",
    serviceType: "prestation",
    icon: Megaphone,
    highlights: ["Ads", "Posts", "Kits réseaux", "Cohérence visuelle"],
    highlightsEn: ["Ads", "Posts", "Social media kits", "Visual consistency"],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },

  // ── DOCUMENTS & OUTILS (inclus abonnement → /abonnement) ─
  {
    slug: "factures-automatiques",
    title: "Factures automatiques",
    excerpt: "Logo + infos société + export : pro en 1 minute.",
    titleEn: "Automated invoices",
    excerptEn: "Logo + company info + export: professional in 1 minute.",
    category: "Documents & Outils",
    serviceType: "outil",
    icon: FileText,
    highlights: ["Templates", "Branding", "Export PDF", "Simple & rapide"],
    highlightsEn: ["Templates", "Branding", "PDF export", "Simple & fast"],
    ctaLabel: "Accéder à l'espace client",
    ctaLabelEn: "Access client area",
    ctaHref: "/abonnement",
  },
  {
    slug: "devis-automatiques",
    title: "Devis automatiques",
    excerpt: "Devis premium : clair, pro, rapide.",
    titleEn: "Automated quotes",
    excerptEn: "Premium quotes: clear, professional, fast.",
    category: "Documents & Outils",
    serviceType: "outil",
    icon: ClipboardList,
    highlights: ["Templates", "Calcul simple", "Export PDF", "Envoi client"],
    highlightsEn: ["Templates", "Simple calculation", "PDF export", "Client delivery"],
    ctaLabel: "Découvrir l'abonnement",
    ctaLabelEn: "Discover the plan",
    ctaHref: "/abonnement",
  },
  {
    slug: "planning-agenda",
    title: "Planning / agenda",
    excerpt: "Organisation claire et efficace.",
    titleEn: "Scheduling / calendar",
    excerptEn: "Clear and efficient organisation.",
    category: "Documents & Outils",
    serviceType: "outil",
    icon: BadgeCheck,
    highlights: ["Vue Jour / Semaine / Mois", "Organisation", "Rappels", "Efficace"],
    highlightsEn: ["Day / Week / Month view", "Organisation", "Reminders", "Efficient"],
    ctaLabel: "Commencer maintenant",
    ctaLabelEn: "Get started now",
    ctaHref: "/abonnement",
  },
  {
    slug: "bloc-notes",
    title: "Bloc-notes",
    excerpt: "Notes rapides + organisation (export possible ensuite).",
    titleEn: "Professional notepad",
    excerptEn: "Quick notes + organisation (export available).",
    category: "Documents & Outils",
    serviceType: "outil",
    icon: NotebookPen,
    highlights: ["Notes par catégorie", "Classement", "Export disponible", "Interface propre"],
    highlightsEn: ["Notes by category", "Filing", "Export available", "Clean interface"],
    ctaLabel: "Voir l'offre pro",
    ctaLabelEn: "View pro plan",
    ctaHref: "/abonnement",
  },

  // ── ACCOMPAGNEMENT (prestations → contact) ───────────────
  {
    slug: "creation-auto-entrepreneur",
    title: "Création auto-entrepreneur",
    excerpt: "Démarrage simple, rapide, clair.",
    titleEn: "Sole trader registration",
    excerptEn: "Simple, fast, clear business setup.",
    category: "Accompagnement",
    serviceType: "prestation",
    icon: Briefcase,
    highlights: ["Guidage", "Dossiers", "Étapes claires", "Soutien"],
    highlightsEn: ["Guidance", "Documents", "Clear steps", "Support"],
    ctaLabel: "Prendre contact",
    ctaLabelEn: "Get in touch",
    ctaHref: "/contact",
  },
  {
    slug: "declarations-urssaf",
    title: "Déclarations URSSAF",
    excerpt: "Assistance administrative personnalisée.",
    titleEn: "URSSAF declarations",
    excerptEn: "Personalised administrative assistance.",
    category: "Accompagnement",
    serviceType: "prestation",
    icon: ClipboardList,
    highlights: ["Suivi", "Conseils", "Aide déclaration", "Sérénité"],
    highlightsEn: ["Follow-up", "Advice", "Declaration assistance", "Peace of mind"],
    ctaLabel: "Prendre contact",
    ctaLabelEn: "Get in touch",
    ctaHref: "/contact",
  },
  {
    slug: "assistance-administrative-entreprises",
    title: "Assistance administrative entreprises",
    excerpt:
      "Gestion documentaire, rédaction professionnelle et organisation interne — on prend en charge votre administratif pour que vous vous concentriez sur l'essentiel.",
    titleEn: "Business administrative assistance",
    excerptEn:
      "Document management, professional writing and internal organisation — we handle your admin so you can focus on what matters.",
    category: "Accompagnement",
    serviceType: "prestation",
    icon: Building2,
    highlights: [
      "Gestion et classement des documents",
      "Rédaction de courriers & emails professionnels",
      "Suivi des échéances légales et fiscales",
      "Tableaux de bord et reporting interne",
      "Préparation des dossiers administratifs",
      "Confidentialité et discrétion garanties",
    ],
    highlightsEn: [
      "Document management and filing",
      "Professional letters & email drafting",
      "Legal and tax deadline monitoring",
      "Internal dashboards and reporting",
      "Administrative file preparation",
      "Guaranteed confidentiality and discretion",
    ],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },
  {
    slug: "fournisseurs-internationaux",
    title: "Recherche de fournisseurs internationaux",
    excerpt:
      "Sourcing qualifié en Chine, Turquie, Dubaï et ailleurs — les meilleurs prix, les bons partenaires, sans les mauvaises surprises.",
    titleEn: "International supplier sourcing",
    excerptEn:
      "Qualified sourcing in China, Turkey, Dubai and beyond — best prices, trusted partners, no bad surprises.",
    category: "Accompagnement",
    serviceType: "prestation",
    icon: Globe,
    highlights: [
      "Sourcing ciblé : Chine, Turquie, Dubaï, Inde…",
      "Vérification et qualification des fournisseurs",
      "Négociation des prix et conditions",
      "Gestion des commandes et des délais",
      "Suivi logistique et douanier",
      "Conseils import-export et réglementation",
    ],
    highlightsEn: [
      "Targeted sourcing: China, Turkey, Dubai, India…",
      "Supplier verification and qualification",
      "Price and terms negotiation",
      "Order and timeline management",
      "Logistics and customs monitoring",
      "Import-export advice and regulations",
    ],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },
  {
    slug: "marches-publics-prives",
    title: "Marchés publics & privés",
    excerpt:
      "Répondez aux appels d'offres avec un dossier solide, clair et convaincant — de la veille jusqu'à la remise du mémoire technique.",
    titleEn: "Public & private tenders",
    excerptEn:
      "Respond to tenders with a solid, clear and compelling application — from monitoring through to technical submission.",
    category: "Accompagnement",
    serviceType: "prestation",
    icon: Landmark,
    highlights: [
      "Veille et détection des appels d'offres",
      "Constitution et vérification du dossier",
      "Rédaction du mémoire technique",
      "Réponse aux questions du commanditaire",
      "Marchés publics et marchés privés",
      "Accompagnement de A à Z",
    ],
    highlightsEn: [
      "Tender monitoring and detection",
      "Application compilation and review",
      "Technical memorandum drafting",
      "Responding to client queries",
      "Public and private tenders",
      "End-to-end support",
    ],
    ctaLabel: "Demander un devis",
    ctaLabelEn: "Request a quote",
    ctaHref: "/contact",
  },

  // ── COACHING ──────────────────────────────────────────────
  {
    slug: "coaching-ia",
    title: "Coaching IA",
    excerpt: "190€ / 3 mois — stratégie + automatisation + support.",
    titleEn: "AI Coaching",
    excerptEn: "€190 / 3 months — strategy + automation + support.",
    category: "Coaching",
    serviceType: "prestation",
    icon: Brain,
    highlights: ["Plan d'action", "Outils IA", "Suivi 3 mois", "Objectifs clairs"],
    highlightsEn: ["Action plan", "AI tools", "3-month follow-up", "Clear objectives"],
    ctaLabel: "Voir l'offre",
    ctaLabelEn: "View offer",
    ctaHref: "/services/coaching-ia",
  },
  {
    slug: "soutien-scolaire",
    title: "Soutien scolaire",
    excerpt: "14€/h — de la 6e à la Terminale — RDV en ligne.",
    titleEn: "Academic tutoring",
    excerptEn: "€14/h — from Year 7 to A-Level — online sessions.",
    category: "Coaching",
    serviceType: "prestation",
    icon: GraduationCap,
    highlights: ["Méthode", "Exercices", "Régularité", "RDV en ligne"],
    highlightsEn: ["Methodology", "Exercises", "Consistency", "Online sessions"],
    ctaLabel: "Prendre RDV",
    ctaLabelEn: "Book a session",
    ctaHref: "/services/soutien-scolaire",
  },
];
